spring:
  application:
    name: springcloud-service-provider

server:
  port: 8081

eureka:
  client:
    service-url:
      # 单机
      defaultZone: http://localhost:8700/eureka/
      # 集群版
      #defaultZone: http://eureka8701:8701/eureka/, http://eureka8702:8702/eureka/, http://eureka8703:8703/eureka/
