spring:
  application:
    name: springcloud-feign-service

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka/
    # 客户端每隔30秒从Eureka服务上更新一次服务信息
    registry-fetch-interval-seconds: 30
    # 将服务注册到eureka上
    register-with-eureka: true
    # 检索服务
    fetch-registry: true
  # 心跳检测检查与续约时间
  instance:
    # 如果10s之内没有给服务端发送心跳，则代表故障，将我剔除掉，默认90s
    lease-expiration-duration-in-seconds: 10
    # 每隔2s向服务端发送一次心跳，证明该服务还活着，默认30s
    lease-renewal-interval-in-seconds: 2

# 开启hystrix熔断机制
feign:
  hystrix:
    enabled: true
