server:
  port: 2002

spring:
  application:
    name: coolw-hystrix-turbine

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka
    # 客户端每隔30秒从Eureka服务上更新一次服务信息
    registry-fetch-interval-seconds: 30
    # 需要将我的服务注册到eureka上
    register-with-eureka: true
    # 需要检索服务
    fetch-registry: true
  # 心跳检测与续约时间
  instance:
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 2
    prefer-ip-address: true
    # 实例名称
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

turbine:
  combine-host-port: true
  # 配置Euraka中的serviceId列表，表明监控哪些服务
  app-config: coolw-consumer-service
  cluster-name-expression: new String('default')