spring:
  application:
    name: coolw-provider-service

server:
  port: 8081

eureka:
  instance:
    # 使用指定的IP注册
    prefer-ip-address: true
  #    ip-address: 127.0.0.1
  client:
    service-url:
      # 单机
      defaultZone: http://localhost:8700/eureka/
      # 集群版
      #defaultZone: http://eureka8701:8701/eureka/, http://eureka8702:8702/eureka/, http://eureka8703:8703/eureka/
