spring:
  application:
    name: springcloud-service-provider

server:
  port: 8080

eureka:
  instance:
    # 使用指定的IP注册
    prefer-ip-address: true
#    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka/
    # 客户端每隔30秒从Eureka服务上更新一次服务信息
    registry-fetch-interval-seconds: 30
    # 需要将我的服务注册到eureka上
    register-with-eureka: true
    # 需要检索服务
    fetch-registry: true

